from typing import Protocol
from .types import EmbeddingRequest, EmbeddingResult, EmbeddingBatchResult

class EmbeddingProvider(Protocol):
    @property
    def metadata(self): ...
    async def embed(self, request: EmbeddingRequest) -> EmbeddingResult: ...
    async def embed_batch(self, requests: tuple[EmbeddingRequest, ...]) -> EmbeddingBatchResult: ...
